UCLALibrary/bucketeer

README.md
- update the README with a URL that produces results, when running the dev Vertx instance.
=> change URL for verification of the dev instance in the README

pom.xml, src/test/resources/settings.xml
The build was copying over a test settings.xml file which we'd normally want but in our case we want to put some additional S3 configuration information in there so we don't want that overridden. This commit disables that behavior by reconfiguring the resources plugin.
=> Fix resource robot gone amuck

src/test/java/edu/ucla/library/bucketeer/handlers/LoadImageHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/verticles/MainVerticleTest.java
The main issue here was there were two different closes of the async task in the test setup. I reorganized the code so that there is now just one. This change is needed for [IIIF-276] to work.
In the process of testing, I made a few other cosmetic changes too.
=> Fix vertx startup in LoadImageHandlerTest + minor tweaks

pom.xml
In order to be able to use an external logging configuration, we need to stop packaging a default logging configuration in the Jar file. This didn't use to be true, but the never JDKs have obsoleted the `-Xbootclasspath/p:[PATH]` option, which is how we were overriding the default location in the jar file.
We'll be able to use `-Xbootclasspath/a` but we need to remove the packaged logging configuration file first. This is fine because we'll be able to supply a default config in the Docker build.
=> Don't package log config with jar

src/main/java/edu/ucla/library/bucketeer/verticles/ImageWorkerVerticle.java, src/main/java/edu/ucla/library/bucketeer/verticles/S3BucketVerticle.java, src/main/resources/bucketeer_messages.xml
* Add better debugging and handle a possible exception that could be thrown if the JPX file can't be read from the local file system for some obscure reason.
* Extend timeout on message response from S3BucketVerticle. This could probably be rewritten to not reply with a response at all, since the message sender is not actually waiting on a response, but that's a future ticket.
This is in support of IIIF-289 but doesn't close it or anything, is just incremental progress.
=> Improve error handling

.travis.yml, trigger-docker-build.sh
This PR aims to fix and improve the following features:
* TravisCI is only configured to run on PRs and master branch. The new PR will accept requests for tags under the semantic version scheme(without the prepended v in front of the numbers, e.g. 1.0.0)
* After success triggered on the each matrix build, which meant 2 curl jobs would run. I moved to using stage builds which runs independently from other matrix builds
* I optimized the stage builds to run stages only when necessary. E.g. it skips the deploy stages if it's a PR build, skips the latest build if it's a tag build, etc.
* Merging this PR would officially enable automatic triggers to the Jenkins/Codebuild pipeline
=> [IIIF-295] Optimize docker build trigger and accept tagged jobs

pom.xml
Snyk flagged security issue with slf4j-ext. This PR updates that and the vertx library.
=> [IIIF-317] Update dependencies

README.md
Oops, I missed an update in the README (renaming /ping to /status). This PR fixes that.
=> Update README to reflect '/status'

pom.xml, src/main/java/edu/ucla/library/bucketeer/Constants.java, src/main/java/edu/ucla/library/bucketeer/handlers/LoadCsvHandler.java, src/main/java/edu/ucla/library/bucketeer/verticles/ImageWorkerVerticle.java, src/main/java/edu/ucla/library/bucketeer/verticles/S3BucketVerticle.java, src/main/resources/bucketeer.yaml, src/main/webroot/upload/csv/index.html, src/test/java/edu/ucla/library/bucketeer/handlers/BatchJobStatusHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/handlers/LoadImageHandlerTest.java
* Add batch job name to s3 uploaded user metadata
* Add image ID to s3 uploaded user metadata
* Change camel case to dash separated params to make their use consistent with S3 canonical user metadata naming rules
* Improved the consistency of use of named ID variables that are not used as file access points
* Update vertx-super-s3 dependency to v1.1.0 (which includes support for PUTing with user metadata)
NOTE: Travis test will fail because vertx-super-s3 dependency hasn't yet hit Maven Central. Will ping reviewers once it does and this PR is ready for review.
=> [IIIF-386] Add batch job name to s3 upload

src/main/java/edu/ucla/library/bucketeer/verticles/ThumbnailVerticle.java
Small fix for an infrequent problem where the thumbnail invalidation path doesn't get added to the XML that's sent to CloudFront.
=> Fix failure to add invalidation path

src/main/java/edu/ucla/library/bucketeer/handlers/BatchJobStatusHandler.java
We changed how the kakadu-lambda-converter handles ID encoding so we need to reflect that change in our checking of the status update too.
=> [IIIF-440] Fix URL encoding issue

src/main/java/edu/ucla/library/bucketeer/handlers/BatchJobStatusHandler.java
Hopefully, the last in a series of URL encoding/decoding changes. Setting the ID in the access URL in the CSV is the last step in the process.
These changes were caused when we corrected our assumption that ARKs would be URL encoded in the CSVs. They won't be.
=> [IIIF-441] Encode the ID when it's added to access copy URL

src/main/java/edu/ucla/library/bucketeer/Item.java, src/main/java/edu/ucla/library/bucketeer/handlers/LoadCsvHandler.java, src/main/java/edu/ucla/library/bucketeer/utils/JobFactory.java, src/main/resources/bucketeer_messages.xml
I introduced a bug with the last commit where Collection items were no longer skipped like they should be. This PR rectifies that and skips items that have specifically had hasFile() set to false (what we do when parsing Collection records from the CSV).
=> [IIIF-455] Skip items that don't have a source file

src/main/java/edu/ucla/library/bucketeer/handlers/BatchJobStatusHandler.java, src/main/java/edu/ucla/library/bucketeer/handlers/GetJobStatusesHandler.java, src/main/java/edu/ucla/library/bucketeer/utils/IFilePathPrefix.java, src/main/java/edu/ucla/library/bucketeer/utils/JobFactory.java, src/main/java/edu/ucla/library/bucketeer/utils/PrefixDeserializer.java, src/main/resources/bucketeer_messages.xml
* Make job's item statuses the source of truth for job completion
* Set workflow state on Collection items too (even though they don't have images)
* Created custom Jackson serializer for classes implementing IFilePathPrefix
* Fix hasFile() issue with displaying workflow statuses in monitoring endpoint
=> [IIIF-459] Make Job's Item statuses the source of truth

src/main/java/edu/ucla/library/bucketeer/utils/JobFactory.java
If an item doesn't have a file, it needs to be failed so it doesn't hang the batch job result.
=> Fail an item if it doesn't have a file set

src/main/java/edu/ucla/library/bucketeer/utils/UCLAFilePathPrefix.java, src/test/java/edu/ucla/library/bucketeer/utils/UCLAFilePathPrefixTest.java
If a file path starts with Masters, we shouldn't be adding it, just use the root dir + the file path.
=> [IIIF-468] Fix broken Masters logic

src/test/java/edu/ucla/library/bucketeer/ImageUploadIT.java, src/test/java/edu/ucla/library/bucketeer/handlers/LoadImageHandlerTest.java
* revise existing unit and integration tests to use a file with a UTF-8-encoded filename
=> [IIIIF-353] revise existing LoadImageHandlerTest and ImageUploadIT to use a UTF8-encoded filename

src/test/scripts/fake-lambda.sh
Just a testing script that I created that I don't want to lose track of (so checking it into `src/test/scripts`). It mimics AWS Lambda responses to complete a batch job on the dev's local machine (without having to connect to Lambda).
=> Add simple fake-lambda test script

pom.xml, src/main/java/edu/ucla/library/bucketeer/Op.java, src/main/java/edu/ucla/library/bucketeer/handlers/GetConfigHandler.java, src/main/java/edu/ucla/library/bucketeer/verticles/MainVerticle.java, src/main/resources/bucketeer.yaml, src/main/webroot/index.html
Populate the home page config options at runtime instead of build time. This adds a new `/config` endpoint to the app (and so OpenAPI spec, documentation, etc.)
=> [IIIF-408] Make home page config opts runtime populated

src/main/java/edu/ucla/library/bucketeer/JobFactory.java, src/main/java/edu/ucla/library/bucketeer/handlers/LoadCsvHandler.java
We have some older CSVs that have other values for structural rows. We want to make sure we don't preserve those values, but use the new STRUCTURAL state.
=> [IIIF-525] Check previous run collection states

src/test/java/edu/ucla/library/bucketeer/handlers/LoadImageHandlerTest.java
Add a new test timeout to LoadImageHandlerTest. It can be added to other problematic tests as they cause problems.
=> Update the test timeout on LoadImageHandlerTest

.travis.yml, pom.xml, src/main/java/edu/ucla/library/bucketeer/Config.java, src/main/java/edu/ucla/library/bucketeer/HTTP.java, src/main/java/edu/ucla/library/bucketeer/Item.java, src/main/java/edu/ucla/library/bucketeer/JobFactory.java, src/main/java/edu/ucla/library/bucketeer/handlers/BatchJobStatusHandler.java, src/main/java/edu/ucla/library/bucketeer/handlers/LoadCsvHandler.java, src/main/resources/bucketeer_messages.xml, src/test/java/edu/ucla/library/bucketeer/ImageUploadIT.java, src/test/java/edu/ucla/library/bucketeer/handlers/AbstractBucketeerHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/handlers/BatchJobStatusHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/handlers/DeleteJobHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/handlers/GetJobStatusesHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/handlers/GetJobsHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/handlers/LoadImageHandlerTest.java, src/test/java/edu/ucla/library/bucketeer/verticles/SlackMessageVerticleTest.java, src/test/resources/json/jobStatuses.json, src/test/resources/test-config.properties
* Check file size before sending image conversion request to AWS Lambda
* Clean up some exception javadocs and an unnecessary throws
* Simplify HTML success and error file serving in LoadCsvHandler
* Cleaned up job-check tests, which before were posting CSVs to test against (not test jobs are inserted into shared data and the tests use those)
* Added catches for previously unhandled exceptions
* Added a `travis_retry` to the Travis config to work around flaky Travis network issues
* Cache local Maven repo for reuse between builds to speed up build time
* Move Maven profile output to installation phase instead of test phase
* Configure Maven/Surefire to fast-fail; after the first failed test, others are skipped
* Uncomment out a particular test we'd set to exclude at some point and fix its …
=> [IIIF-786] Add source file size check
